"""
Agent 5B — AC Challenger (Adversarial)
Phase       : Refinement
PACT        : Proactive
Classification: True AI (Sonnet 4.6)
Confidence  : Tier B (base=60)

Runs in Batch 3 of the Refinement phase, in parallel with Agent 6 (Test Design Strategy).
Receives Agent 5's AC clauses from state and plays the adversary role.

Game theory principle — Minimax:
  Agent 5 is the Proposer; Agent 5B is the Challenger.
  ACs that survive adversarial challenge are demonstrably stronger.
  Agent 9 (Risk Anticipation) uses challenge_findings as an additional risk signal.

Purpose:
  Stress-test the acceptance criteria generated by Agent 5 by playing the role
  of a hostile FCA inspector, looking for weaknesses in each BDD clause:
    - Ambiguous Given steps (test data setup cannot be reproduced)
    - Non-observable Then outcomes (cannot assert without internal system access)
    - Missing error paths that an FCA auditor would expect to see tested
    - Weak regulatory scenario coverage (COBS 9.2, Consumer Duty, FG21/1)
    - Untestable clauses (vague, unmeasurable, or contradictory)

Output data keys consumed by downstream:
  challenge_findings      → list  (Agent 9 risk signal)
  survivor_count          → int   (Agent 5 confidence adjustment)
  critical_weakness_count → int   (Gate G1 context, CO email)
  challenge_summary       → str   (CO email, Jira comment)
"""

from __future__ import annotations

from src.agents.base import TierBScorer, build_system, call_with_tool
from src.core.config import settings
from src.core.schemas import AgentResult, ConfidenceBreakdown, StoryState

AGENT_ID = 54  # Registered as 54 in AGENT_REGISTRY; conceptually "Agent 05B"
AGENT_NAME = "AC Challenger"

# ── Tool schema ───────────────────────────────────────────────────────────────

_FINDING_SCHEMA = {
    "type": "object",
    "required": ["clause_index", "scenario", "weakness_type", "severity", "detail"],
    "properties": {
        "clause_index": {
            "type": "integer",
            "minimum": 0,
            "description": "Zero-based index of the challenged AC clause.",
        },
        "scenario": {
            "type": "string",
            "description": "The Scenario title from the challenged clause.",
        },
        "weakness_type": {
            "type": "string",
            "enum": [
                "ambiguous_given",
                "non_observable_then",
                "missing_error_path",
                "weak_regulatory",
                "untestable",
            ],
            "description": (
                "ambiguous_given: Given steps are under-specified or non-reproducible. "
                "non_observable_then: Then outcomes cannot be asserted without system internals. "
                "missing_error_path: A failure mode an FCA auditor would expect is absent. "
                "weak_regulatory: Regulatory clause does not cite the specific rule or obligation. "
                "untestable: Clause is vague, contradictory, or logically unmeasurable."
            ),
        },
        "severity": {
            "type": "string",
            "enum": ["CRITICAL", "MAJOR", "MINOR"],
            "description": (
                "CRITICAL: weakness would cause the test to give false confidence — "
                "a defect could pass this AC in production. "
                "MAJOR: weakness significantly reduces test value; should be fixed before sprint start. "
                "MINOR: weakness reduces clarity or maintainability but does not create false confidence."
            ),
        },
        "detail": {
            "type": "string",
            "description": "One concrete sentence describing the specific weakness and why it matters.",
        },
    },
}

_TOOL_NAME = "challenge_ac_clauses"
_TOOL_DESCRIPTION = (
    "Adversarially review the AC clauses proposed by the AC Generator. "
    "Identify specific weaknesses that would allow a defect to pass testing undetected. "
    "Return findings and survivor count."
)
_TOOL_SCHEMA = {
    "type": "object",
    "required": [
        "challenge_summary",
        "survivor_count",
        "critical_weakness_count",
        "challenge_findings",
    ],
    "properties": {
        "challenge_summary": {
            "type": "string",
            "description": (
                "2–3 sentences summarising the overall quality of the AC clauses. "
                "Written to be included in the CO sign-off email for HIGH-FCA stories."
            ),
        },
        "survivor_count": {
            "type": "integer",
            "minimum": 0,
            "description": "Number of AC clauses with NO critical or major weaknesses.",
        },
        "critical_weakness_count": {
            "type": "integer",
            "minimum": 0,
            "description": "Total number of CRITICAL-severity findings across all clauses.",
        },
        "challenge_findings": {
            "type": "array",
            "items": _FINDING_SCHEMA,
            "description": (
                "All weaknesses found, ordered CRITICAL → MAJOR → MINOR. "
                "If a clause is strong with no weaknesses, do NOT add a finding for it. "
                "An empty array means all clauses survived the challenge."
            ),
        },
    },
}

# ── Agent instructions ────────────────────────────────────────────────────────

_AGENT_INSTRUCTIONS = """
You are the AC Challenger Agent for the FSC Agentic QE Framework.

Your role is adversarial: play the part of a hostile FCA inspector reviewing BDD acceptance
criteria for a Salesforce FSC Wealth Management story. Your goal is to find every weakness
that would allow a defect to reach production undetected.

You are NOT being asked to rewrite the ACs. You are asked to identify specific, concrete
weaknesses. Be precise — cite the exact Given/When/Then step that is weak and explain why.

Weakness types to look for:

1. ambiguous_given
   The Given steps do not specify enough test data state for a QE engineer to reproduce the
   scenario reliably. Examples: field values are unspecified, record relationships are vague,
   a prerequisite Apex class or Flow is referenced but not confirmed active.

2. non_observable_then
   The Then outcomes cannot be verified by an automated test or a manual tester without
   accessing system internals, debug logs, or private Apex state. Examples: "the system
   calculates internally", "a background process runs", "the score is updated eventually".

3. missing_error_path
   An FCA auditor reviewing this story would expect a specific failure mode to be tested
   but it is absent. Examples: missing null-check AC for a required field, no test for
   concurrent update race conditions on a suitability field, no test for governor limit
   breach on a bulk Apex trigger.

4. weak_regulatory
   A regulatory AC clause does not cite the specific FCA rule, COBS section, or Consumer
   Duty outcome it is testing. An auditor cannot map the clause to the obligation without
   additional research. All regulatory clauses must include the specific rule reference.

5. untestable
   The clause is logically vague, contradictory, or cannot be asserted with a pass/fail
   outcome. Examples: "the system behaves correctly", "performance is acceptable",
   "the adviser is satisfied".

Severity guidance:
  CRITICAL : the weakness creates false confidence — a real defect could pass this AC.
  MAJOR    : the weakness significantly reduces test value; fix before sprint start.
  MINOR    : reduces clarity or maintainability; fix before automation.

If a clause has no weaknesses, do NOT include it in challenge_findings.
survivor_count = number of clauses with no CRITICAL or MAJOR weaknesses.

Use the challenge_ac_clauses tool to return your assessment.
""".strip()


# ── Main entry point ──────────────────────────────────────────────────────────

async def run(state: StoryState) -> AgentResult:
    story_id = state["story_id"]

    # Read Agent 5's AC clauses from state
    agent5_result = state["agent_results"].get("5", {})
    agent5_data = agent5_result.get("data", {})
    ac_clauses = agent5_data.get("ac_clauses", [])
    ac_count = len(ac_clauses)
    fca_class = agent5_data.get("fca_classification_context", state.get("fca_classification", "UNCLASSIFIED"))

    if ac_count == 0:
        # Agent 5 produced no clauses — nothing to challenge
        return _no_clauses_result(story_id, fca_class)

    user_message = _build_user_message(story_id, fca_class, ac_clauses)

    extracted = await call_with_tool(
        model=settings.default_model,
        system=build_system(_AGENT_INSTRUCTIONS),
        user_message=user_message,
        tool_name=_TOOL_NAME,
        tool_description=_TOOL_DESCRIPTION,
        tool_schema=_TOOL_SCHEMA,
        max_tokens=2000,
    )

    findings = extracted.get("challenge_findings", [])
    survivor_count = extracted.get("survivor_count", ac_count)
    critical_count = extracted.get("critical_weakness_count", 0)
    summary = extracted.get("challenge_summary", "")

    confidence_score, signals = _compute_confidence(
        ac_count, survivor_count, critical_count, findings
    )
    escalated = confidence_score < settings.confidence_escalation_threshold

    what = (
        f"AC Challenger reviewed {ac_count} clause(s) for {story_id}: "
        f"{survivor_count} survived, {critical_count} critical weakness(es) found"
    )
    why = (
        f"Adversarial AC challenge for a {fca_class}-FCA story. "
        f"{len(findings)} finding(s) across {ac_count} clause(s). "
        f"Survivor rate: {survivor_count}/{ac_count}."
    )

    data = {
        "ac_count_challenged": ac_count,
        "survivor_count": survivor_count,
        "critical_weakness_count": critical_count,
        "challenge_findings": findings,
        "challenge_summary": summary,
        "fca_classification_context": fca_class,
        "signals": signals,
    }

    return AgentResult(
        agent_id=AGENT_ID,
        agent_name=AGENT_NAME,
        what=what,
        why=why,
        data=data,
        confidence=ConfidenceBreakdown(
            tier="B",
            raw_score=confidence_score,
            calibration_multiplier=1.0,
            final_score=confidence_score,
            signals=signals,
            escalated=escalated,
        ),
        model_used=settings.default_model,
    )


# ── Confidence scoring (Tier B) ───────────────────────────────────────────────

def _compute_confidence(
    ac_count: int,
    survivor_count: int,
    critical_count: int,
    findings: list,
) -> tuple[int, dict]:
    scorer = TierBScorer(base=60)

    # Signal 1: clauses to challenge (more clauses = richer basis for assessment)
    if ac_count >= 8:
        scorer.add("rich_ac_set", ac_count, +8)
    elif ac_count >= 4:
        scorer.add("adequate_ac_set", ac_count, +4)
    elif ac_count == 0:
        scorer.add("no_acs_to_challenge", 0, -15)

    # Signal 2: survivor rate (high survival = ACs are strong = challenge is well-grounded)
    if ac_count > 0:
        survival_rate = survivor_count / ac_count
        if survival_rate >= 0.8:
            scorer.add("high_survival_rate", round(survival_rate, 2), +8)
        elif survival_rate >= 0.5:
            scorer.add("moderate_survival_rate", round(survival_rate, 2), +3)
        else:
            scorer.add("low_survival_rate", round(survival_rate, 2), -5)

    # Signal 3: critical weaknesses found (finding CRITICAL issues is the job — reward it)
    if critical_count > 0:
        scorer.add("critical_weaknesses_found", critical_count, +5)

    # Signal 4: finding diversity (multiple weakness types = thorough review)
    weakness_types = {f.get("weakness_type") for f in findings if f.get("weakness_type")}
    if len(weakness_types) >= 3:
        scorer.add("diverse_findings", len(weakness_types), +5)

    scorer.cap(92).floor(20)
    return scorer.build()


# ── Helpers ───────────────────────────────────────────────────────────────────

def _no_clauses_result(story_id: str, fca_class: str) -> AgentResult:
    return AgentResult(
        agent_id=AGENT_ID,
        agent_name=AGENT_NAME,
        what=f"AC Challenger skipped for {story_id}: Agent 5 produced no AC clauses to challenge",
        why="Cannot challenge an empty AC set — Agent 5 must generate clauses first.",
        data={
            "ac_count_challenged": 0,
            "survivor_count": 0,
            "critical_weakness_count": 0,
            "challenge_findings": [],
            "challenge_summary": "No AC clauses available to challenge.",
            "fca_classification_context": fca_class,
            "signals": {"no_acs": True},
        },
        confidence=ConfidenceBreakdown(
            tier="B",
            raw_score=20,
            calibration_multiplier=1.0,
            final_score=20,
            signals={"no_acs": True},
            escalated=True,
        ),
        model_used=settings.default_model,
    )


def _build_user_message(
    story_id: str,
    fca_class: str,
    ac_clauses: list[dict],
) -> str:
    lines = [
        f"Adversarially review the following {len(ac_clauses)} AC clause(s) for story {story_id}.",
        f"FCA Classification: {fca_class}",
        "",
        "AC CLAUSES TO CHALLENGE:",
    ]
    for i, clause in enumerate(ac_clauses):
        lines.append(f"\n[Clause {i}] {clause.get('scenario', 'Unknown scenario')}")
        lines.append(f"  scenario_type : {clause.get('scenario_type', 'unknown')}")
        lines.append(f"  test_category : {clause.get('test_category', 'unknown')}")
        lines.append(f"  fca_relevant  : {clause.get('fca_relevant', False)}")
        for given in clause.get("given", []):
            lines.append(f"  {given}")
        for when in clause.get("when", []):
            lines.append(f"  {when}")
        for then in clause.get("then", []):
            lines.append(f"  {then}")

    lines.append(
        f"\nIdentify every weakness using the {_TOOL_NAME} tool. "
        "Only include clauses that have genuine weaknesses in challenge_findings."
    )
    return "\n".join(lines)
