"""
Tests for Agent 9 — Risk Anticipation (True AI).

Confidence scoring is the primary unit-test target.
Integration tests mock Jira and the LLM call.
"""

from unittest.mock import AsyncMock, patch

import pytest

from src.agents.refinement.agent_09_risk_anticipation import (
    _build_user_message,
    _compute_confidence,
    _count_available_agents,
    _RISK_ITEM_SCHEMA,
    _TOOL_NAME,
    _TOOL_SCHEMA,
    run,
)
from src.core.schemas import initial_story_state

# Empty state used by confidence-scoring unit tests (no agent data needed)
_EMPTY_STATE = initial_story_state("FSC-2417")


# ── Fixtures ──────────────────────────────────────────────────────────────────

STORY_SUITABILITY = {
    "story_id": "FSC-2417",
    "summary": "Record Suitability Assessment for Retirement Portfolio",
    "description": (
        "As a Wealth Adviser, I want to record a COBS 9.2 Suitability Assessment "
        "for a client's retirement portfolio. The Suitability__c record must link "
        "to the client's RiskProfile__c and the relevant FinancialAccount."
    ),
    "status": "Sprint Ready",
    "issue_type": "Story",
    "priority": "High",
    "labels": [],
    "components": ["Suitability"],
    "assignee": "dev@firm.com",
    "reporter": "po@firm.com",
}

AGENT3_AGREED = {
    "fca_classification": "HIGH",
    "ensemble_agreement": True,
    "fca_triggers": ["Suitability__c", "RiskProfile__c"],
}

AGENT3_DISAGREED = {
    "fca_classification": "HIGH",
    "ensemble_agreement": False,
    "fca_triggers": ["Suitability__c"],
}

AGENT4_AT_RISK = {
    "cd_verdict": "AT_RISK",
    "vulnerable_customer_impact": True,
    "cd_risks": ["Consumer Duty Outcome 1 gap — vulnerable customer pathway unclear"],
    "cd_obligations": ["PS22/9 Outcome 1"],
    "cd_evidence_required": True,
}

AGENT4_COMPLIANT = {
    "cd_verdict": "COMPLIANT",
    "vulnerable_customer_impact": False,
    "cd_risks": [],
    "cd_obligations": [],
    "cd_evidence_required": False,
}

AGENT5_GENERATED = {
    "generation_mode": "generated_from_scratch",
    "ac_clause_count": 4,
    "remaining_gaps": ["No error path for invalid RiskProfile state"],
    "coverage_assessment": {
        "happy_path": True,
        "error_paths": False,
        "edge_cases": False,
        "regulatory": True,
    },
}

AGENT5_VALIDATED = {
    "generation_mode": "validated_existing",
    "ac_clause_count": 6,
    "remaining_gaps": [],
    "coverage_assessment": {
        "happy_path": True,
        "error_paths": True,
        "edge_cases": True,
        "regulatory": True,
    },
}

AGENT8_DEEP = {
    "detected_objects": ["suitability__c", "riskprofile__c"],
    "implied_objects": ["financialaccount"],
    "dependency_depth": 3,
}

AGENT8_SHALLOW = {
    "detected_objects": ["financialaccount"],
    "implied_objects": [],
    "dependency_depth": 0,
}

MOCK_RISK_CRITICAL = {
    "risk_register": [
        {
            "risk_id": "R-001",
            "category": "consumer_duty",
            "description": "Vulnerable customer pathway missing Consumer Duty confirmation step.",
            "severity": "CRITICAL",
            "mitigation": "Add Consumer Duty confirmation screen to Suitability flow for VulnerableCustomerIndicator__c = true.",
            "source_agent": "agent_4",
        },
        {
            "risk_id": "R-002",
            "category": "regulatory",
            "description": "No test evidence for COBS 9.2 suitability obligation.",
            "severity": "HIGH",
            "mitigation": "Add regulatory scenario in CRT covering COBS 9.2 compliance check.",
            "source_agent": "agent_3",
        },
        {
            "risk_id": "R-003",
            "category": "quality",
            "description": "ACs generated by AI — not PO-authored.",
            "severity": "MEDIUM",
            "mitigation": "Product Owner to review and approve generated ACs before sprint start.",
            "source_agent": "agent_5",
        },
    ],
    "critical_risk_count": 1,
    "high_risk_count": 1,
    "overall_risk_level": "CRITICAL",
    "risk_summary": (
        "This HIGH-FCA story carries a CRITICAL Consumer Duty risk due to the vulnerable customer "
        "pathway lacking a confirmation step. A HIGH regulatory risk exists as no COBS 9.2 test "
        "evidence scenario is documented. Product Owner sign-off on AI-generated ACs is required."
    ),
    "recommended_actions": [
        "CRITICAL: Add Consumer Duty confirmation step to Suitability flow for vulnerable customers.",
        "HIGH: Add COBS 9.2 regulatory test scenario to CRT.",
        "MEDIUM: Product Owner to review AI-generated ACs before sprint start.",
    ],
}

MOCK_RISK_LOW = {
    "risk_register": [
        {
            "risk_id": "R-001",
            "category": "quality",
            "description": "Minor label change — low inherent risk.",
            "severity": "LOW",
            "mitigation": "Smoke test the button label on the Account page after deployment.",
            "source_agent": "agent_1",
        },
    ],
    "critical_risk_count": 0,
    "high_risk_count": 0,
    "overall_risk_level": "LOW",
    "risk_summary": "This low-risk UI label change has no FCA implications and minimal test risk.",
    "recommended_actions": ["Smoke test button label post-deployment."],
}

_AGENT1_MINIMAL = {
    "goal": "Record suitability assessment",
    "persona": "Wealth Adviser",
    "fsc_objects": ["suitability__c"],
    "flags": [],
    "missing_elements": [],
}

AGENT5B_CLEAN = {
    "ac_count_challenged": 3, "survivor_count": 3, "critical_weakness_count": 0,
    "challenge_findings": [], "challenge_summary": "All ACs passed.",
}

AGENT5B_MINOR = {
    "ac_count_challenged": 3, "survivor_count": 1, "critical_weakness_count": 2,
    "challenge_findings": [], "challenge_summary": "Minor issues found.",
}

AGENT5B_FAILED = {
    "ac_count_challenged": 3, "survivor_count": 0, "critical_weakness_count": 3,
    "challenge_findings": [], "challenge_summary": "Major weaknesses.",
}

MOCK_RISK_EMPTY = {
    "risk_register": [], "critical_risk_count": 0, "high_risk_count": 0,
    "overall_risk_level": "LOW", "risk_summary": "No risks.", "recommended_actions": [],
}


def _build_msg_defaults(**agent_kwargs):
    """Call _build_user_message with STORY_SUITABILITY, only the named agents populated."""
    a1 = agent_kwargs.get("a1")
    a2 = agent_kwargs.get("a2")
    a3 = agent_kwargs.get("a3")
    a4 = agent_kwargs.get("a4")
    a5 = agent_kwargs.get("a5")
    a6 = agent_kwargs.get("a6")
    a7 = agent_kwargs.get("a7")
    a8 = agent_kwargs.get("a8")
    a5b = agent_kwargs.get("a5b")
    return _build_user_message(
        STORY_SUITABILITY,
        a1, 85 if a1 else 0,
        a2, 85 if a2 else 0,
        a3, 85 if a3 else 0,
        a4, 85 if a4 else 0,
        a5, 85 if a5 else 0,
        a6, 85 if a6 else 0,
        a7, 85 if a7 else 0,
        a8, 85 if a8 else 0,
        a5b, 85 if a5b else 0,
    )


# ── Confidence scoring unit tests ─────────────────────────────────────────────

def _conf(a3, a3_c, a4, a5, a5b, a8, extracted):
    """Shorthand to call _compute_confidence with default empty state."""
    return _compute_confidence(a3, a3_c, a4, a5, a5b, a8, extracted, _EMPTY_STATE)


class TestConfidenceScoring:
    def test_ensemble_agreement_boosts_confidence(self):
        score_agreed, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        score_disagreed, _ = _conf(AGENT3_DISAGREED, 55, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert score_agreed > score_disagreed

    def test_agent3_unavailable_reduces_confidence(self):
        score_with, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        score_without, _ = _conf(None, 0, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert score_with > score_without

    def test_agent4_available_boosts_confidence(self):
        score_with, _ = _conf(AGENT3_AGREED, 85, AGENT4_AT_RISK, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        score_without, _ = _conf(AGENT3_AGREED, 85, None, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert score_with > score_without

    def test_cd_at_risk_boosts_confidence(self):
        """Confirmed AT_RISK verdict grounds the risk register — adds confidence."""
        score_at_risk, _ = _conf(AGENT3_AGREED, 85, AGENT4_AT_RISK, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_CRITICAL)
        score_compliant, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_CRITICAL)
        assert score_at_risk >= score_compliant

    def test_deep_dependency_boosts_confidence(self):
        score_deep, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_DEEP, MOCK_RISK_LOW)
        score_shallow, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert score_deep > score_shallow

    def test_remaining_ac_gaps_reduce_confidence(self):
        score_gaps, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_GENERATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        score_no_gaps, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert score_gaps < score_no_gaps

    def test_generated_from_scratch_reduces_confidence(self):
        score_gen, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_GENERATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        score_val, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert score_gen < score_val

    def test_rich_risk_register_boosts_confidence(self):
        score_rich, _ = _conf(AGENT3_AGREED, 85, AGENT4_AT_RISK, AGENT5_GENERATED, None, AGENT8_DEEP, MOCK_RISK_CRITICAL)
        score_sparse, _ = _conf(AGENT3_AGREED, 85, AGENT4_AT_RISK, AGENT5_GENERATED, None, AGENT8_DEEP, MOCK_RISK_LOW)
        assert score_rich > score_sparse

    def test_critical_risks_present_boosts_confidence(self):
        score_critical, _ = _conf(AGENT3_AGREED, 85, AGENT4_AT_RISK, AGENT5_VALIDATED, None, AGENT8_DEEP, MOCK_RISK_CRITICAL)
        score_low, signals_low = _conf(AGENT3_AGREED, 85, AGENT4_AT_RISK, AGENT5_VALIDATED, None, AGENT8_DEEP, MOCK_RISK_LOW)
        assert score_critical > score_low
        assert "critical_risks_identified" not in signals_low

    def test_score_never_exceeds_92(self):
        score, _ = _conf(AGENT3_AGREED, 85, AGENT4_AT_RISK, AGENT5_VALIDATED, None, AGENT8_DEEP, MOCK_RISK_CRITICAL)
        assert score <= 92

    def test_score_never_below_20(self):
        score, _ = _conf(None, 0, None, None, None, None, MOCK_RISK_LOW)
        assert score >= 20

    def test_ensemble_disagreement_signal_recorded(self):
        _, signals = _conf(AGENT3_DISAGREED, 55, None, None, None, None, MOCK_RISK_LOW)
        assert "agent3_disagreed_ta" in signals

    def test_agent3_unavailable_signal_recorded(self):
        _, signals = _conf(None, 0, None, None, None, None, MOCK_RISK_LOW)
        assert "agent3_unavailable" in signals

    def test_ac_challenge_passed_signal(self):
        _, signals = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, AGENT5B_CLEAN, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert "ac_challenge_passed" in signals

    def test_ac_challenge_minor_issues_signal(self):
        _, signals = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, AGENT5B_MINOR, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert "ac_challenge_minor_issues" in signals

    def test_ac_challenge_failed_signal(self):
        _, signals = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, AGENT5B_FAILED, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert "ac_challenge_failed" in signals

    def test_empty_risk_register_signal(self):
        _, signals = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_EMPTY)
        assert "empty_risk_register" in signals

    def test_no_dependencies_signal(self):
        _, signals = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert "no_dependencies" in signals

    def test_agent3_agreed_weighted_stores_confidence(self):
        _, signals = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert signals["agent3_agreed_weighted"] == 85

    def test_agent4_available_key_in_signals(self):
        _, signals = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert "agent4_available" in signals

    def test_cd_risk_confirmed_stores_verdict(self):
        _, signals = _conf(AGENT3_AGREED, 85, AGENT4_AT_RISK, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert signals["cd_risk_confirmed"] == "AT_RISK"

    def test_dependency_depth_rich_stores_depth(self):
        _, signals = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_DEEP, MOCK_RISK_LOW)
        assert signals["dependency_depth_rich"] == 3

    def test_remaining_ac_gaps_stores_count(self):
        _, signals = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_GENERATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert signals["remaining_ac_gaps"] == 1

    def test_acs_generated_not_authored_key_in_signals(self):
        _, signals = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_GENERATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert "acs_generated_not_authored" in signals


# ── Helper unit tests ─────────────────────────────────────────────────────────

class TestCountAvailableAgents:
    def test_counts_present_agents(self):
        state = initial_story_state("FSC-2417")
        state["agent_results"]["1"] = {"data": {}}
        state["agent_results"]["3"] = {"data": {}}
        state["agent_results"]["8"] = {"data": {}}
        assert _count_available_agents(state) == 3

    def test_empty_state_returns_zero(self):
        state = initial_story_state("FSC-2417")
        assert _count_available_agents(state) == 0

    def test_all_eight_agents_present(self):
        state = initial_story_state("FSC-2417")
        for i in range(1, 9):
            state["agent_results"][str(i)] = {"data": {}}
        assert _count_available_agents(state) == 8

    def test_counts_agent_54(self):
        state = initial_story_state("FSC-2417")
        state["agent_results"]["54"] = {"data": {}}
        assert _count_available_agents(state) == 1


# ── Integration tests — full agent run ───────────────────────────────────────

@pytest.mark.asyncio
class TestAgentRun:
    async def test_returns_agent_result(self):
        state = initial_story_state("FSC-2417")
        state["agent_results"]["3"] = {"data": AGENT3_AGREED}
        state["agent_results"]["4"] = {"data": AGENT4_AT_RISK}

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        assert result.agent_id == 9
        assert result.agent_name == "Risk Anticipation"
        assert result.confidence.tier == "B"

    async def test_data_has_required_downstream_keys(self):
        state = initial_story_state("FSC-2417")
        state["agent_results"]["3"] = {"data": AGENT3_AGREED}

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        for key in ["risk_register", "critical_risk_count", "high_risk_count",
                    "overall_risk_level", "risk_summary", "recommended_actions"]:
            assert key in result.data

    async def test_critical_risk_count_propagated(self):
        state = initial_story_state("FSC-2417")
        state["agent_results"]["4"] = {"data": AGENT4_AT_RISK}

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        assert result.data["critical_risk_count"] == 1
        assert result.data["overall_risk_level"] == "CRITICAL"

    async def test_risk_register_length_in_data(self):
        state = initial_story_state("FSC-2417")

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        assert result.data["risk_count"] == len(MOCK_RISK_CRITICAL["risk_register"])

    async def test_runs_standalone_without_upstream_data(self):
        """Agent 9 must function even if no upstream agents ran."""
        state = initial_story_state("FSC-2417")

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_LOW
            result = await run(state)

        assert result.agent_id == 9
        assert result.data["upstream_agents_available"] == 0

    async def test_upstream_agent_count_tracked(self):
        state = initial_story_state("FSC-2417")
        for i in ["1", "3", "4", "8"]:
            state["agent_results"][i] = {"data": {}}

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        assert result.data["upstream_agents_available"] == 4

    async def test_fca_context_from_agent3_used(self):
        state = initial_story_state("FSC-2417")
        state["agent_results"]["3"] = {"data": AGENT3_AGREED}

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        assert result.data["fca_classification_context"] == "HIGH"

    async def test_uses_default_model(self):
        state = initial_story_state("FSC-2417")

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_LOW
            result = await run(state)

        assert result.model_used == "claude-sonnet-4-6"

    async def test_ta_interaction_summary_in_data(self):
        state = initial_story_state("FSC-2417")
        state["agent_results"]["3"] = {"data": AGENT3_AGREED}

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        assert "ta_interaction_summary" in result.data
        summary = result.data["ta_interaction_summary"]
        for agent_id in ["1", "2", "3", "4", "5", "54", "6", "8"]:
            assert agent_id in summary
            assert summary[agent_id] in ("OK", "NOT_OK")

    async def test_ta_interaction_summary_ok_when_high_confidence(self):
        state = initial_story_state("FSC-2417")
        # Agent 3 with confidence >= 60 should be marked OK
        state["agent_results"]["3"] = {
            "data": AGENT3_AGREED,
            "confidence": {"final_score": 85},
        }

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        assert result.data["ta_interaction_summary"]["3"] == "OK"

    async def test_unavailable_agent3_causes_escalation(self):
        state = initial_story_state("FSC-2417")

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_LOW
            result = await run(state)

        assert result.confidence.escalated is True

    async def test_what_contains_story_id(self):
        state = initial_story_state("FSC-2417")

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_LOW
            result = await run(state)

        assert "FSC-2417" in result.what

    async def test_signals_key_in_data_is_dict(self):
        state = initial_story_state("FSC-2417")

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_LOW
            result = await run(state)

        assert isinstance(result.data["signals"], dict)


# ── TA confidence penalty tests ────────────────────────────────────────────────

class TestTAPenalties:
    def test_disagreement_penalises_more_than_agreement(self):
        score_agreed, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        score_disagreed, _ = _conf(AGENT3_DISAGREED, 55, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert score_agreed > score_disagreed

    def test_disagreement_signal_records_ta_key(self):
        _, signals = _conf(AGENT3_DISAGREED, 55, None, None, None, None, MOCK_RISK_LOW)
        assert any("agent3_disagreed" in k for k in signals)


# ── REQ-07: new risk signal tests ────────────────────────────────────────────

AGENT5_WITH_VC_COVERAGE = {
    "generation_mode": "validated_existing",
    "ac_clause_count": 6,
    "remaining_gaps": [],
    "coverage_assessment": {
        "happy_path": True,
        "error_paths": True,
        "edge_cases": True,
        "regulatory": True,
        "vulnerable_customer": True,
    },
}

AGENT5_MISSING_VC_COVERAGE = {
    "generation_mode": "validated_existing",
    "ac_clause_count": 5,
    "remaining_gaps": [],
    "coverage_assessment": {
        "happy_path": True,
        "error_paths": True,
        "edge_cases": True,
        "regulatory": True,
        "vulnerable_customer": False,
    },
}

AGENT6_WITH_POSTMAN = {
    "coverage_target_pct": 85,
    "test_tools": ["ApexUnit", "CRT", "Postman"],
    "risk_areas": [],
}

AGENT6_WITHOUT_POSTMAN = {
    "coverage_target_pct": 85,
    "test_tools": ["ApexUnit", "CRT"],
    "risk_areas": [],
}

AGENT7_NO_FCA_CONTEXT = {
    "data_volume": "complex",
    "sensitive_data_present": False,
    "fca_context_available": False,
    "risks": [],
}

AGENT7_WITH_FCA_CONTEXT = {
    "data_volume": "complex",
    "sensitive_data_present": False,
    "fca_context_available": True,
    "risks": [],
}

AGENT8_WITH_EXTERNAL_DEPS = {
    "detected_objects": ["suitability__c"],
    "implied_objects": [],
    "dependency_depth": 1,
    "has_external_dependencies": True,
    "detected_dependency_types": ["external_service"],
}

AGENT8_WITH_PLATFORM_EVENT = {
    "detected_objects": ["suitability__c"],
    "implied_objects": [],
    "dependency_depth": 1,
    "has_external_dependencies": True,
    "detected_dependency_types": ["platform_event"],
}

AGENT8_NO_EXTERNAL_DEPS = {
    "detected_objects": ["suitability__c"],
    "implied_objects": [],
    "dependency_depth": 1,
    "has_external_dependencies": False,
    "detected_dependency_types": [],
}


@pytest.mark.asyncio
class TestNewRiskSignalsREQ07:
    async def test_vc_impact_true_no_vc_scenario_in_prompt(self):
        """REQ-07: vulnerable_customer_impact=True + coverage.vulnerable_customer=False → risk signal in prompt."""
        state = initial_story_state("FSC-2417")
        state["agent_results"]["4"] = {"data": AGENT4_AT_RISK}  # vc_impact=True
        state["agent_results"]["5"] = {"data": AGENT5_MISSING_VC_COVERAGE}

        captured_user_message = None

        async def capture_call(**kwargs):
            nonlocal captured_user_message
            captured_user_message = kwargs.get("user_message", "")
            return MOCK_RISK_CRITICAL

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  side_effect=capture_call),
        ):
            mock_story.return_value = STORY_SUITABILITY
            await run(state)

        assert "vulnerable_customer=False" in captured_user_message

    async def test_fca_context_unavailable_in_prompt(self):
        """REQ-07: fca_context_available=False from Agent 07 surfaces in the prompt."""
        state = initial_story_state("FSC-2417")
        state["agent_results"]["7"] = {"data": AGENT7_NO_FCA_CONTEXT}

        captured_user_message = None

        async def capture_call(**kwargs):
            nonlocal captured_user_message
            captured_user_message = kwargs.get("user_message", "")
            return MOCK_RISK_LOW

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  side_effect=capture_call),
        ):
            mock_story.return_value = STORY_SUITABILITY
            await run(state)

        assert "FCA Context Available: False" in captured_user_message

    async def test_external_deps_without_postman_in_prompt(self):
        """REQ-07: has_external_dependencies=True without Postman in Agent 6 test_tools → both surfaced."""
        state = initial_story_state("FSC-2417")
        state["agent_results"]["6"] = {"data": AGENT6_WITHOUT_POSTMAN}
        state["agent_results"]["8"] = {"data": AGENT8_WITH_EXTERNAL_DEPS}

        captured_user_message = None

        async def capture_call(**kwargs):
            nonlocal captured_user_message
            captured_user_message = kwargs.get("user_message", "")
            return MOCK_RISK_LOW

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  side_effect=capture_call),
        ):
            mock_story.return_value = STORY_SUITABILITY
            await run(state)

        assert "Has External Dependencies: True" in captured_user_message
        assert "Postman" not in captured_user_message.split("Test Tools:")[1].split("\n")[0]

    async def test_platform_event_dependency_type_in_prompt(self):
        """REQ-07: platform_event in detected_dependency_types surfaces in prompt."""
        state = initial_story_state("FSC-2417")
        state["agent_results"]["8"] = {"data": AGENT8_WITH_PLATFORM_EVENT}

        captured_user_message = None

        async def capture_call(**kwargs):
            nonlocal captured_user_message
            captured_user_message = kwargs.get("user_message", "")
            return MOCK_RISK_LOW

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  side_effect=capture_call),
        ):
            mock_story.return_value = STORY_SUITABILITY
            await run(state)

        assert "platform_event" in captured_user_message

    async def test_test_tools_list_in_prompt(self):
        """REQ-07: Agent 6 test_tools appear in prompt so Sonnet can detect missing Postman."""
        state = initial_story_state("FSC-2417")
        state["agent_results"]["6"] = {"data": AGENT6_WITH_POSTMAN}

        captured_user_message = None

        async def capture_call(**kwargs):
            nonlocal captured_user_message
            captured_user_message = kwargs.get("user_message", "")
            return MOCK_RISK_LOW

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  side_effect=capture_call),
        ):
            mock_story.return_value = STORY_SUITABILITY
            await run(state)

        assert "Test Tools:" in captured_user_message
        assert "Postman" in captured_user_message


# ── Prompt content tests ─────────────────────────────────────────────────────

class TestBuildUserMessage:
    def test_includes_story_id(self):
        msg = _build_msg_defaults()
        assert "FSC-2417" in msg

    def test_includes_summary(self):
        msg = _build_msg_defaults()
        assert STORY_SUITABILITY["summary"] in msg

    def test_includes_note_confidence_instruction(self):
        msg = _build_msg_defaults()
        assert "NOTE:" in msg

    def test_agent1_section_present_when_provided(self):
        msg = _build_msg_defaults(a1=_AGENT1_MINIMAL)
        assert "AGENT 1 — STORY INTENT" in msg

    def test_agent1_section_absent_when_none(self):
        msg = _build_msg_defaults()
        assert "AGENT 1" not in msg

    def test_agent3_shows_ensemble_agreement(self):
        msg = _build_msg_defaults(a3=AGENT3_AGREED)
        assert "Ensemble Agreement:" in msg

    def test_agent4_shows_verdict(self):
        msg = _build_msg_defaults(a4=AGENT4_AT_RISK)
        assert "Verdict:" in msg

    def test_agent5_shows_vulnerable_customer_field(self):
        msg = _build_msg_defaults(a5=AGENT5_WITH_VC_COVERAGE)
        assert "vulnerable_customer=" in msg

    def test_agent5b_section_present_when_provided(self):
        msg = _build_msg_defaults(a5b=AGENT5B_CLEAN)
        assert "AGENT 5B — AC CHALLENGER" in msg

    def test_agent5b_section_absent_when_none(self):
        msg = _build_msg_defaults()
        assert "AGENT 5B" not in msg

    def test_agent6_shows_test_tools(self):
        msg = _build_msg_defaults(a6=AGENT6_WITH_POSTMAN)
        assert "Test Tools:" in msg

    def test_agent7_shows_fca_context_available(self):
        msg = _build_msg_defaults(a7=AGENT7_NO_FCA_CONTEXT)
        assert "FCA Context Available:" in msg

    def test_agent8_shows_has_external_dependencies(self):
        msg = _build_msg_defaults(a8=AGENT8_WITH_EXTERNAL_DEPS)
        assert "Has External Dependencies:" in msg

    def test_ends_with_tool_name_and_risk_register(self):
        msg = _build_msg_defaults()
        assert _TOOL_NAME in msg
        assert msg.strip().endswith("risk register.")


# ── Schema contract tests ─────────────────────────────────────────────────────

class TestSchemaContract:
    def test_tool_schema_has_six_required_fields(self):
        expected = {
            "critical_risk_count", "high_risk_count", "overall_risk_level",
            "risk_summary", "recommended_actions", "risk_register",
        }
        assert set(_TOOL_SCHEMA["required"]) == expected

    def test_risk_register_is_array(self):
        assert _TOOL_SCHEMA["properties"]["risk_register"]["type"] == "array"

    def test_risk_item_schema_has_six_required_fields(self):
        expected = {"risk_id", "category", "description", "severity", "mitigation", "source_agent"}
        assert set(_RISK_ITEM_SCHEMA["required"]) == expected

    def test_category_enum_has_five_values(self):
        schema = _RISK_ITEM_SCHEMA["properties"]["category"]
        assert schema["enum"] == ["regulatory", "consumer_duty", "technical", "data", "quality"]

    def test_severity_enum_has_four_values(self):
        schema = _RISK_ITEM_SCHEMA["properties"]["severity"]
        assert schema["enum"] == ["CRITICAL", "HIGH", "MEDIUM", "LOW"]

    def test_critical_risk_count_minimum_zero(self):
        assert _TOOL_SCHEMA["properties"]["critical_risk_count"]["minimum"] == 0

    def test_high_risk_count_minimum_zero(self):
        assert _TOOL_SCHEMA["properties"]["high_risk_count"]["minimum"] == 0

    def test_overall_risk_level_enum_has_four_values(self):
        schema = _TOOL_SCHEMA["properties"]["overall_risk_level"]
        assert schema["enum"] == ["CRITICAL", "HIGH", "MEDIUM", "LOW"]

    def test_recommended_actions_is_array_of_strings(self):
        items = _TOOL_SCHEMA["properties"]["recommended_actions"]["items"]
        assert items["type"] == "string"
