"""
Tests for Agent 9 — Risk Anticipation (True AI).

Confidence scoring is the primary unit-test target.
Integration tests mock Jira and the LLM call.
"""

from unittest.mock import AsyncMock, patch

import pytest

from src.agents.refinement.agent_09_risk_anticipation import (
    _compute_confidence,
    _count_available_agents,
    run,
)
from src.core.schemas import initial_story_state

# Empty state used by confidence-scoring unit tests (no agent data needed)
_EMPTY_STATE = initial_story_state("FSC-2417")


# ── Fixtures ──────────────────────────────────────────────────────────────────

STORY_SUITABILITY = {
    "story_id": "FSC-2417",
    "summary": "Record Suitability Assessment for Retirement Portfolio",
    "description": (
        "As a Wealth Adviser, I want to record a COBS 9.2 Suitability Assessment "
        "for a client's retirement portfolio. The Suitability__c record must link "
        "to the client's RiskProfile__c and the relevant FinancialAccount."
    ),
    "status": "Sprint Ready",
    "issue_type": "Story",
    "priority": "High",
    "labels": [],
    "components": ["Suitability"],
    "assignee": "dev@firm.com",
    "reporter": "po@firm.com",
}

AGENT3_AGREED = {
    "fca_classification": "HIGH",
    "ensemble_agreement": True,
    "fca_triggers": ["Suitability__c", "RiskProfile__c"],
}

AGENT3_DISAGREED = {
    "fca_classification": "HIGH",
    "ensemble_agreement": False,
    "fca_triggers": ["Suitability__c"],
}

AGENT4_AT_RISK = {
    "cd_verdict": "AT_RISK",
    "vulnerable_customer_impact": True,
    "cd_risks": ["Consumer Duty Outcome 1 gap — vulnerable customer pathway unclear"],
    "cd_obligations": ["PS22/9 Outcome 1"],
    "cd_evidence_required": True,
}

AGENT4_COMPLIANT = {
    "cd_verdict": "COMPLIANT",
    "vulnerable_customer_impact": False,
    "cd_risks": [],
    "cd_obligations": [],
    "cd_evidence_required": False,
}

AGENT5_GENERATED = {
    "generation_mode": "generated_from_scratch",
    "ac_clause_count": 4,
    "remaining_gaps": ["No error path for invalid RiskProfile state"],
    "coverage_assessment": {
        "happy_path": True,
        "error_paths": False,
        "edge_cases": False,
        "regulatory": True,
    },
}

AGENT5_VALIDATED = {
    "generation_mode": "validated_existing",
    "ac_clause_count": 6,
    "remaining_gaps": [],
    "coverage_assessment": {
        "happy_path": True,
        "error_paths": True,
        "edge_cases": True,
        "regulatory": True,
    },
}

AGENT8_DEEP = {
    "detected_objects": ["suitability__c", "riskprofile__c"],
    "implied_objects": ["financialaccount"],
    "dependency_depth": 3,
}

AGENT8_SHALLOW = {
    "detected_objects": ["financialaccount"],
    "implied_objects": [],
    "dependency_depth": 0,
}

MOCK_RISK_CRITICAL = {
    "risk_register": [
        {
            "risk_id": "R-001",
            "category": "consumer_duty",
            "description": "Vulnerable customer pathway missing Consumer Duty confirmation step.",
            "severity": "CRITICAL",
            "mitigation": "Add Consumer Duty confirmation screen to Suitability flow for VulnerableCustomerIndicator__c = true.",
            "source_agent": "agent_4",
        },
        {
            "risk_id": "R-002",
            "category": "regulatory",
            "description": "No test evidence for COBS 9.2 suitability obligation.",
            "severity": "HIGH",
            "mitigation": "Add regulatory scenario in CRT covering COBS 9.2 compliance check.",
            "source_agent": "agent_3",
        },
        {
            "risk_id": "R-003",
            "category": "quality",
            "description": "ACs generated by AI — not PO-authored.",
            "severity": "MEDIUM",
            "mitigation": "Product Owner to review and approve generated ACs before sprint start.",
            "source_agent": "agent_5",
        },
    ],
    "critical_risk_count": 1,
    "high_risk_count": 1,
    "overall_risk_level": "CRITICAL",
    "risk_summary": (
        "This HIGH-FCA story carries a CRITICAL Consumer Duty risk due to the vulnerable customer "
        "pathway lacking a confirmation step. A HIGH regulatory risk exists as no COBS 9.2 test "
        "evidence scenario is documented. Product Owner sign-off on AI-generated ACs is required."
    ),
    "recommended_actions": [
        "CRITICAL: Add Consumer Duty confirmation step to Suitability flow for vulnerable customers.",
        "HIGH: Add COBS 9.2 regulatory test scenario to CRT.",
        "MEDIUM: Product Owner to review AI-generated ACs before sprint start.",
    ],
}

MOCK_RISK_LOW = {
    "risk_register": [
        {
            "risk_id": "R-001",
            "category": "quality",
            "description": "Minor label change — low inherent risk.",
            "severity": "LOW",
            "mitigation": "Smoke test the button label on the Account page after deployment.",
            "source_agent": "agent_1",
        },
    ],
    "critical_risk_count": 0,
    "high_risk_count": 0,
    "overall_risk_level": "LOW",
    "risk_summary": "This low-risk UI label change has no FCA implications and minimal test risk.",
    "recommended_actions": ["Smoke test button label post-deployment."],
}


# ── Confidence scoring unit tests ─────────────────────────────────────────────

def _conf(a3, a3_c, a4, a5, a5b, a8, extracted):
    """Shorthand to call _compute_confidence with default empty state."""
    return _compute_confidence(a3, a3_c, a4, a5, a5b, a8, extracted, _EMPTY_STATE)


class TestConfidenceScoring:
    def test_ensemble_agreement_boosts_confidence(self):
        score_agreed, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        score_disagreed, _ = _conf(AGENT3_DISAGREED, 55, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert score_agreed > score_disagreed

    def test_agent3_unavailable_reduces_confidence(self):
        score_with, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        score_without, _ = _conf(None, 0, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert score_with > score_without

    def test_agent4_available_boosts_confidence(self):
        score_with, _ = _conf(AGENT3_AGREED, 85, AGENT4_AT_RISK, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        score_without, _ = _conf(AGENT3_AGREED, 85, None, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert score_with > score_without

    def test_cd_at_risk_boosts_confidence(self):
        """Confirmed AT_RISK verdict grounds the risk register — adds confidence."""
        score_at_risk, _ = _conf(AGENT3_AGREED, 85, AGENT4_AT_RISK, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_CRITICAL)
        score_compliant, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_CRITICAL)
        assert score_at_risk >= score_compliant

    def test_deep_dependency_boosts_confidence(self):
        score_deep, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_DEEP, MOCK_RISK_LOW)
        score_shallow, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert score_deep > score_shallow

    def test_remaining_ac_gaps_reduce_confidence(self):
        score_gaps, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_GENERATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        score_no_gaps, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert score_gaps < score_no_gaps

    def test_generated_from_scratch_reduces_confidence(self):
        score_gen, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_GENERATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        score_val, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert score_gen < score_val

    def test_rich_risk_register_boosts_confidence(self):
        score_rich, _ = _conf(AGENT3_AGREED, 85, AGENT4_AT_RISK, AGENT5_GENERATED, None, AGENT8_DEEP, MOCK_RISK_CRITICAL)
        score_sparse, _ = _conf(AGENT3_AGREED, 85, AGENT4_AT_RISK, AGENT5_GENERATED, None, AGENT8_DEEP, MOCK_RISK_LOW)
        assert score_rich > score_sparse

    def test_critical_risks_present_boosts_confidence(self):
        score_critical, _ = _conf(AGENT3_AGREED, 85, AGENT4_AT_RISK, AGENT5_VALIDATED, None, AGENT8_DEEP, MOCK_RISK_CRITICAL)
        score_low, signals_low = _conf(AGENT3_AGREED, 85, AGENT4_AT_RISK, AGENT5_VALIDATED, None, AGENT8_DEEP, MOCK_RISK_LOW)
        assert score_critical > score_low
        assert "critical_risks_identified" not in signals_low

    def test_score_never_exceeds_92(self):
        score, _ = _conf(AGENT3_AGREED, 85, AGENT4_AT_RISK, AGENT5_VALIDATED, None, AGENT8_DEEP, MOCK_RISK_CRITICAL)
        assert score <= 92

    def test_score_never_below_20(self):
        score, _ = _conf(None, 0, None, None, None, None, MOCK_RISK_LOW)
        assert score >= 20

    def test_ensemble_disagreement_signal_recorded(self):
        _, signals = _conf(AGENT3_DISAGREED, 55, None, None, None, None, MOCK_RISK_LOW)
        assert "agent3_disagreed_ta" in signals

    def test_agent3_unavailable_signal_recorded(self):
        _, signals = _conf(None, 0, None, None, None, None, MOCK_RISK_LOW)
        assert "agent3_unavailable" in signals


# ── Helper unit tests ─────────────────────────────────────────────────────────

class TestCountAvailableAgents:
    def test_counts_present_agents(self):
        state = initial_story_state("FSC-2417")
        state["agent_results"]["1"] = {"data": {}}
        state["agent_results"]["3"] = {"data": {}}
        state["agent_results"]["8"] = {"data": {}}
        assert _count_available_agents(state) == 3

    def test_empty_state_returns_zero(self):
        state = initial_story_state("FSC-2417")
        assert _count_available_agents(state) == 0

    def test_all_eight_agents_present(self):
        state = initial_story_state("FSC-2417")
        for i in range(1, 9):
            state["agent_results"][str(i)] = {"data": {}}
        assert _count_available_agents(state) == 8


# ── Integration tests — full agent run ───────────────────────────────────────

@pytest.mark.asyncio
class TestAgentRun:
    async def test_returns_agent_result(self):
        state = initial_story_state("FSC-2417")
        state["agent_results"]["3"] = {"data": AGENT3_AGREED}
        state["agent_results"]["4"] = {"data": AGENT4_AT_RISK}

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        assert result.agent_id == 9
        assert result.agent_name == "Risk Anticipation"
        assert result.confidence.tier == "B"

    async def test_data_has_required_downstream_keys(self):
        state = initial_story_state("FSC-2417")
        state["agent_results"]["3"] = {"data": AGENT3_AGREED}

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        for key in ["risk_register", "critical_risk_count", "high_risk_count",
                    "overall_risk_level", "risk_summary", "recommended_actions"]:
            assert key in result.data

    async def test_critical_risk_count_propagated(self):
        state = initial_story_state("FSC-2417")
        state["agent_results"]["4"] = {"data": AGENT4_AT_RISK}

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        assert result.data["critical_risk_count"] == 1
        assert result.data["overall_risk_level"] == "CRITICAL"

    async def test_risk_register_length_in_data(self):
        state = initial_story_state("FSC-2417")

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        assert result.data["risk_count"] == len(MOCK_RISK_CRITICAL["risk_register"])

    async def test_runs_standalone_without_upstream_data(self):
        """Agent 9 must function even if no upstream agents ran."""
        state = initial_story_state("FSC-2417")

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_LOW
            result = await run(state)

        assert result.agent_id == 9
        assert result.data["upstream_agents_available"] == 0

    async def test_upstream_agent_count_tracked(self):
        state = initial_story_state("FSC-2417")
        for i in ["1", "3", "4", "8"]:
            state["agent_results"][i] = {"data": {}}

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        assert result.data["upstream_agents_available"] == 4

    async def test_fca_context_from_agent3_used(self):
        state = initial_story_state("FSC-2417")
        state["agent_results"]["3"] = {"data": AGENT3_AGREED}

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        assert result.data["fca_classification_context"] == "HIGH"

    async def test_uses_default_model(self):
        state = initial_story_state("FSC-2417")

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_LOW
            result = await run(state)

        assert result.model_used == "claude-sonnet-4-6"

    async def test_ta_interaction_summary_in_data(self):
        state = initial_story_state("FSC-2417")
        state["agent_results"]["3"] = {"data": AGENT3_AGREED}

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        assert "ta_interaction_summary" in result.data
        summary = result.data["ta_interaction_summary"]
        for agent_id in ["1", "2", "3", "4", "5", "54", "6", "8"]:
            assert agent_id in summary
            assert summary[agent_id] in ("OK", "NOT_OK")

    async def test_ta_interaction_summary_ok_when_high_confidence(self):
        state = initial_story_state("FSC-2417")
        # Agent 3 with confidence >= 60 should be marked OK
        state["agent_results"]["3"] = {
            "data": AGENT3_AGREED,
            "confidence": {"final_score": 85},
        }

        with (
            patch("src.agents.refinement.agent_09_risk_anticipation.get_story",
                  new_callable=AsyncMock) as mock_story,
            patch("src.agents.refinement.agent_09_risk_anticipation.call_with_tool",
                  new_callable=AsyncMock) as mock_llm,
        ):
            mock_story.return_value = STORY_SUITABILITY
            mock_llm.return_value = MOCK_RISK_CRITICAL
            result = await run(state)

        assert result.data["ta_interaction_summary"]["3"] == "OK"


# ── TA confidence penalty tests ────────────────────────────────────────────────

class TestTAPenalties:
    def test_disagreement_penalises_more_than_agreement(self):
        score_agreed, _ = _conf(AGENT3_AGREED, 85, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        score_disagreed, _ = _conf(AGENT3_DISAGREED, 55, AGENT4_COMPLIANT, AGENT5_VALIDATED, None, AGENT8_SHALLOW, MOCK_RISK_LOW)
        assert score_agreed > score_disagreed

    def test_disagreement_signal_records_ta_key(self):
        _, signals = _conf(AGENT3_DISAGREED, 55, None, None, None, None, MOCK_RISK_LOW)
        assert any("agent3_disagreed" in k for k in signals)
